export default {
  MOVIES: "MOVIES",
  CURRENT_PAGE: "CURRENT_PAGE",
  TOGGLE_LOADER: "TOGGLE_LOADER",
  REMOVE_ITEM: "REMOVE_ITEM",
  TOGGLE_SEARCH: "TOGGLE_SEARCH",
  SHOW_TOAST_NOTIFY: "SHOW_TOAST_NOTIFY",
};
